### ISSUE TITLE
can you write an Arduino code for panasonic an5192k?

### ISSUE THREAD

**Issue by Nonstopxiaowei** [skumlos/tb1226en-i2c-bridge#1]
can you write an Arduino code for panasonic an5192k?  : )   thank you

**Comment by skumlos** [comment]
I don't have any hardware using this jungle so writing anything against it is really hard, as I don't know what the problem relates to...

**Comment by Nonstopxiaowei** [comment]
OK. I see. Thank you very much. 😊

Martin Hejnfelt <notifications@github.com> 于2021年2月14日周日 下午10:20写道：
