### ISSUE TITLE
3d printed scart connector holder

### ISSUE THREAD

**Issue by NO-ob** [skumlos/tb1226en-i2c-bridge#2]
Hi would you be able to share the model for the 3d printed part you used to hold the scart connector for the TM-A140PN please. Also what scart connector did you use for it?

Thankyou

**Comment by skumlos** [comment]
That one was a pretty ugly one-off thing I did at the time (the holes for the RCAs were drilled in, why is why they're not completely in-line). Nowadays I use this:https://www.thingiverse.com/thing:3685684 along with the board for it.

The SCART connector used in the original A140PN was this https://www.tme.eu/en/details/scart-17/euro-hdmi-connectors/ninigi/

**Comment by NO-ob** [comment]
Cool thankyou ill give some of those pcbs ordered
